from app.models.watchlist_stock import WatchlistStock
from app.models import db, WatchlistStock
from datetime import date

def seed_watchlist_stocks():
    demo_watchlist_stock_1 = WatchlistStock(watchlist_id=1, ticker="GBTC")
    demo_watchlist_stock_2 = WatchlistStock(watchlist_id=1, ticker="NVDA")
    demo_watchlist_stock_3 = WatchlistStock(watchlist_id=1, ticker="INTC")
    demo_watchlist_stock_4 = WatchlistStock(watchlist_id=1, ticker="PYPL")
    demo_watchlist_stock_5 = WatchlistStock(watchlist_id=1, ticker="BABA")

    demo_watchlist_stock_6 = WatchlistStock(watchlist_id=2, ticker="GME")
    demo_watchlist_stock_7 = WatchlistStock(watchlist_id=1, ticker="BBY")
    demo_watchlist_stock_8 = WatchlistStock(watchlist_id=2, ticker="DOGE")
    demo_watchlist_stock_9 = WatchlistStock(watchlist_id=3, ticker="F")
    demo_watchlist_stock_10 = WatchlistStock(watchlist_id=1, ticker="XOM")
    demo_watchlist_stock_11 = WatchlistStock(watchlist_id=1, ticker="T")
    demo_watchlist_stock_12 = WatchlistStock(watchlist_id=2, ticker="JNJ")
    demo_watchlist_stock_13 = WatchlistStock(watchlist_id=2, ticker="DIS")
    demo_watchlist_stock_14 = WatchlistStock(watchlist_id=1, ticker="PTON")
    demo_watchlist_stock_15 = WatchlistStock(watchlist_id=1, ticker="ETH.X")
    demo_watchlist_stock_16 = WatchlistStock(watchlist_id=2, ticker="ONTX")
    demo_watchlist_stock_17 = WatchlistStock(watchlist_id=3, ticker="POAHY")
    demo_watchlist_stock_18 = WatchlistStock(watchlist_id=3, ticker="GM")
    demo_watchlist_stock_19 = WatchlistStock(watchlist_id=3, ticker="HMC")
    demo_watchlist_stock_20 = WatchlistStock(watchlist_id=4, ticker="SJM")
    demo_watchlist_stock_21 = WatchlistStock(watchlist_id=4, ticker="NSRGY")
    demo_watchlist_stock_22 = WatchlistStock(watchlist_id=4, ticker="QSR")
    demo_watchlist_stock_23 = WatchlistStock(watchlist_id=4, ticker="SBUX")
    demo_watchlist_stock_24 = WatchlistStock(watchlist_id=5, ticker="SFM")
    demo_watchlist_stock_25 = WatchlistStock(watchlist_id=5, ticker="SPTN")
    demo_watchlist_stock_26 = WatchlistStock(watchlist_id=5, ticker="HLF")

    db.session.add(demo_watchlist_stock_1)
    db.session.add(demo_watchlist_stock_2)
    db.session.add(demo_watchlist_stock_3)
    db.session.add(demo_watchlist_stock_4)
    db.session.add(demo_watchlist_stock_5)
    db.session.add(demo_watchlist_stock_6)
    db.session.add(demo_watchlist_stock_7)
    db.session.add(demo_watchlist_stock_8)
    db.session.add(demo_watchlist_stock_9)
    db.session.add(demo_watchlist_stock_10)
    db.session.add(demo_watchlist_stock_11)
    db.session.add(demo_watchlist_stock_12)
    db.session.add(demo_watchlist_stock_13)
    db.session.add(demo_watchlist_stock_14)
    db.session.add(demo_watchlist_stock_15)
    db.session.add(demo_watchlist_stock_16)
    db.session.add(demo_watchlist_stock_17)
    db.session.add(demo_watchlist_stock_18)
    db.session.add(demo_watchlist_stock_19)
    db.session.add(demo_watchlist_stock_20)
    db.session.add(demo_watchlist_stock_21)
    db.session.add(demo_watchlist_stock_22)
    db.session.add(demo_watchlist_stock_23)
    db.session.add(demo_watchlist_stock_24)
    db.session.add(demo_watchlist_stock_25)
    db.session.add(demo_watchlist_stock_26)

    db.session.commit()


def undo_watchlist_stocks():
    db.session.execute('TRUNCATE watchlist_stocks RESTART IDENTITY CASCADE;')
    db.session.commit()